require('./app.js');
require('./js/services/socket.js');
require('./js/kvoxctrl.js');
require('./js/kvoxformctrl.js');
require('./js/queue.ctrl.js');
require('./js/songbookctrl.js');
require('./js/renderer.ctrl.js');
require('./js/admin.ctrl.js');
require('./js/ngLoadScript');
